version: '3.9'

services:

  load_balancer:
    build: load_balancer/ # Path to the Dockerfile for the client
    image: load_balancer_img
    container_name: load_balancer_con
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      network1:
        aliases:
          - load_balancer

  server:
    build: server/
    image: server_img
    container_name: server1  # This is not needed as docker-compose will create a unique name for each container
    ports:
    # host:container port mapping
    # fixing host port makes it same for all containers, causing conflicts, hence not specified
      - "5000:5000"  # What does 5000:5000 in assignment mean?
    networks:
      network1:
        aliases:
          - server1
    # removed this since server.py sets server name based on SERVER_ID env variable, so all servers respond with the same name
    environment:
      SERVER_ID: server1
    # deploy:
    #   replicas: 3 

networks:
  network1:
    name: mynet