version: '3.9'

services:

  client:
    build: doc_client/ # Path to the Dockerfile for the client
    image: client_img
    container_name: client_con
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      network1:
        aliases:
          - client

  server:
    build: doc_server/
    image: server_img
    container_name: server1
    ports:
      - "5000:5000"
    networks:
      network1:
        aliases:
          - server1
    environment:
      SERVER_ID: server1

networks:
  network1:
    name: mynet